[package]
name = "da14531"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
vcell = "0.1"

[dependencies.cortex-m-rt]
optional = true
version = "0.7"

[features]
rt = ["cortex-m-rt/device"]